### ISSUE TITLE
Is there a way to make specific changes to the state that don't create an entry in the history?

### ISSUE THREAD

**Issue by banglashi** [WHenderson/svelte-immer-store#1]
Hi @WHenderson 
There are some changes to the state that I would like not to persist in the history. Is this something that would makes sense to implement?

**Comment by WHenderson** [comment]
Hi @banglashi , if you change the 3rd argument to the immerStore you can change what gets stored.
In the case above, simply return immediately when you don't want to store anything.

e.g.

```javascript

const history = new History();
const enqueueChange = (change) => {
  if (ignore) {
    return;
  }
  else {
    return history.enqueue(change);
  }
}

immerStore(undefined, () => {}, enqueueChange);
```

Look at `History._enqueue` for the current implementation if you want to do anything advanced or create your own derived History class.

**Comment by banglashi** [comment]
Hi @WHenderson thanks for your feedback. That works for me.
