### ISSUE TITLE
Creating a `.select()` store for each item in an array

### ISSUE THREAD

**Issue by alexlafroscia** [WHenderson/svelte-immer-store#3]
#### Perceived Problem

I want to dynamically iterate over each item in an array (within an `ImmerStore`) and create a store for that array element (via `.select()`)

#### Ideas / Proposed Solution(s)

I was able to achieve this manually like so, but it feels like a hack... 

```ts
export let store: ImmerStore<any[]>;

const childStores = derived(store, (current) => {
  return current.map((_value, index) => {
    return store.select((current) => current[index]);
  });
});
```

Now each `childStores` member can be manipulated as expected 🎉 

I'm not sure what kind of API would be possible to support my use-case, but it would be awesome if `ImmerStore<any[]>` was iterable, where each member was the same as having called `.select` with the index, so that something like this would "just work"

```svelte
<script>
  export let store: ImmerStore<string[]>;

  function addString() {
    store.update(current => [...current, '']);
  }
</script>

<button on:click={addString}>Add another one</button>

{#each store as stringStore}
  <input type="text" bind:value={$stringStore} />
{/each}
```

**Comment by WHenderson** [comment]
To iterate over the store contents, you'll need to get the store contents. (We can't know the length of the contents without interrogation).
To update a specific store value, you'll need a store (via select) for that specific item.

Combining this, I first imagined something like this:
https://svelte.dev/repl/d3fff15708a7453590363498ef80ffb8?version=3.47.0

But you'll quickly see the error - svelte still has some limitations with respect to stores :-(

To workaround this, you'll need to create a component for each instance such as:
https://svelte.dev/repl/026c5e6e35f0481eb7757d2c2de905c4?version=3.47.0

I'm hoping they remove this limitation, but for now this should be able to get you over the hump.

If you find a better workaround do let me know.
