### ISSUE TITLE
warning : Sourcemap points to missing source files

### ISSUE THREAD

**Issue by gterras** [WHenderson/svelte-immer-store#5]
Hi, 

First of all thanks for this wonderful lib! I was able to set up a very complex dynamic form (including dynamic listeners per field) from a very simple non-reactive definition, all of this with a ridiculously short amount of lines of code <3

Running latest SvelteKit in dev mode I get the following warning: 

```
Sourcemap for "~/project/node_modules/svelte-immer-store/dist-esm/index.js" points to missing source files
Sourcemap for "~/project/node_modules/svelte-immer-store/dist-esm/immer-store.js" points to missing source files
Sourcemap for "~/project/node_modules/svelte-immer-store/dist-esm/history.js" points to missing source files
Sourcemap for "~/project/node_modules/svelte-immer-store/dist-esm/workaround.js" points to missing source files
Sourcemap for "~/project/node_modules/svelte-immer-store/dist-esm/proxy/path.js" points to missing source files
Sourcemap for "~/project/node_modules/svelte-immer-store/dist-esm/proxy/tracker.js" points to missing source files
``` 

Note sure if it's related to Vite or this package. 

Thanks

**Comment by WHenderson** [comment]
Likely something wrong with the build or distribution step in the lib.
Do you have steps to reproduce?

I really wish building an npm distribution was a little more strait forward!

**Comment by gterras** [comment]
Hi thanks I will provide a repro repo in a few days.

**Comment by WHenderson** [comment]
I've inlined the sources. Hopefully that fixes it

**Comment by gterras** [comment]
Nice I will try this out, thank you !
