### ISSUE TITLE
import {noop} from "svelte/internal" is breaking in Svelte 5 

### ISSUE THREAD

**Issue by janzheng** [WHenderson/svelte-immer-store#6]
#### Screenshot
![image](https://github.com/user-attachments/assets/13e6aae7-d15e-4dd4-9161-9010b152a6f7)

#### Description

Svelte 5 doesn't compile if any packages references "svelte/internal"

#### Repro Steps/Link 

Importing `svelte-immer-store` in a project will cause the project to not compile in Svelte 5

**Comment by WHenderson** [comment]
I've updated the library to avoid using svelte/internal now. Hopefully that should resolve your issues

**Comment by janzheng** [comment]
thanks!!
